### ISSUE TITLE
docker image: sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by yodog** [CorralPeltzer/newTrackon#264]
using the provided docker compose yaml and the latest image, the container stops with the error below:

```
root@1037u:~# docker logs torrent-newtrackon-1

2023-12-12 14:58:29,148 [INFO] [newtrackon] Server started
Traceback (most recent call last):
  File "/app/newTrackon/run.py", line 34, in <module>
    db.ensure_db_existence()
  File "/app/newTrackon/newTrackon/db.py", line 14, in ensure_db_existence
    create_db()
  File "/app/newTrackon/newTrackon/db.py", line 18, in create_db
    conn = sqlite3.connect(db_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
```

i tried both with local volumes and without any volumes. same result.

**Comment by yodog** [comment]
hey @CorralPeltzer can you believe after almost 3 years im stuck at this again?

the container should support bind mounts, right? why cant it find the database?

```
newtrackon  | 2026-06-03 16:13:12,328 [INFO] [newtrackon] Server started
newtrackon  | Traceback (most recent call last):
newtrackon  |   File "/app/newTrackon/run.py", line 31, in <module>
newtrackon  |     db.ensure_db_existence()
newtrackon  |     ~~~~~~~~~~~~~~~~~~~~~~^^
newtrackon  |   File "/app/newTrackon/newTrackon/db.py", line 15, in ensure_db_existence
newtrackon  |     create_db()
newtrackon  |     ~~~~~~~~~^^
newtrackon  |   File "/app/newTrackon/newTrackon/db.py", line 19, in create_db
newtrackon  |     conn = sqlite3.connect(db_file)
newtrackon  | sqlite3.OperationalError: unable to open database file
```

PS: i tried with your docker compose and got the same error. must be something with the latest docker image.
